# Generated by Django 4.0 on 2022-01-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_review_body_alter_review_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="got_review",
            field=models.BooleanField(default=False),
        ),
    ]
