# Generated by Django 4.0 on 2022-01-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_ticket_got_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="management.ticket"
            ),
        ),
    ]
