# Generated by Django 4.0 on 2022-01-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_alter_review_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
    ]
